jobs:
- name: u16javall-test
  type: runSh
  steps:
    - TASK:
        runtime:
          options:
            imageName: "drydock/u16javall"
            imageTag: master
        script:
           - shipctl jdk set openjdk7
           - shipctl jdk set openjdk8
           - shipctl jdk set openjdk9
           - shipctl jdk set oraclejdk10
           - shipctl jdk set oraclejdk10
           - mvn --version
           - ant -version
           - gradle --version 
           
